dist: trusty

language: python
python: 3.6

branches:
  only:
  - test
  - stable
  - staging
  - production

cache: pip

before_install:
#- openssl aes-256-cbc -K $encrypted_596a6d1c4f83_key -iv $encrypted_596a6d1c4f83_iv -in deploy-key.enc -out deploy-key -d
#- rm deploy-key.enc
#- chmod 600 deploy-key
#- mv deploy-key ~/.ssh/id_rsa
#- eval "$(ssh-agent -s)"
#- ssh-add ~/.ssh/id_rsa

install:
- pip install ansible
- pip install -r requirements.txt

before_script:
- sudo mkdir /var/log/etsin_finder
- sudo chown -R $USER:$USER /var/log/etsin_finder

script:
- coverage run --source="etsin_finder"
- coverage report -m
- cd etsin_finder
- flake8 .

#notifications:
#  flowdock:

after_success:
- $TRAVIS_BUILD_DIR/.travis-deploy.sh
