dist: trusty

language: python
python: 3.6

branches:
  only:
  - test
  - stable
  - staging
  - production

cache: pip

#addons:
#  postgresql: '9.6'

#services:
#- postgresql

before_install:
#- openssl aes-256-cbc -K $encrypted_596a6d1c4f83_key -iv $encrypted_596a6d1c4f83_iv -in deploy-key.enc -out deploy-key -d
#- rm deploy-key.enc
#- chmod 600 deploy-key
#- mv deploy-key ~/.ssh/id_rsa
#- eval "$(ssh-agent -s)"
#- ssh-add ~/.ssh/id_rsa

install:
- pip install ansible
- pip install -r requirements.txt
#- sudo service postgresql restart

before_script:
#- psql -U postgres < resources/sql/init_test.sql
- sudo mkdir /var/log/etsin-finder
- sudo chown -R $USER:$USER /var/log/etsin-finder

script:
- cd src
- flake8 .
#- coverage run --source="." manage.py test metax_api
#- COVERALLS_REPO_TOKEN=$coveralls_token coveralls

#notifications:
#  flowdock:

after_success:
- $TRAVIS_BUILD_DIR/.travis-deploy.sh


