version: '3.8'
services:
    etsin-qvain-webpack:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-qvain-webpack
      command: npm start
      volumes:
        - ./etsin_finder/:/etsin_finder/
      depends_on:
        - backend
      environment:
        - CHOKIDAR_USEPOLLING=true
        - base_url=0.0.0.0:8080
    etsin-qvain-flask:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-qvain-flask
      configs:
        - source: etsin-qvain-app-config
          target: /home/etsin-user/app_config
      ports:
        - "5000:5000"
      volumes:
        - ./etsin_finder/:/etsin_finder/
      environment:
        - base_url=0.0.0.0:5000
        - FLASK_ENV=development
        - PYTHONPATH=/
        - FLASK_DEBUG=1
    etsin-qvain-elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
      environment:
        - base_url=0.0.0.0:9201
        - http.host=0.0.0.0
        - transport.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    etsin-qvain-nginx:
      image: nginx
      configs:
        - source: etsin-qvain-nginx-config
          target: /etc/nginx/nginx.conf
        - source: fairdata-ssl-certificate
          target: /etc/nginx/ssl_certs/ssl.crt.pem
        - source: fairdata-ssl-certificate-key
          target: /etc/nginx/ssl_certs/ssl.key.pem
        - source: etsin-qvain-nginx-dhparam
          target: /etc/nginx/ssl_certs/dhparam.pem
      ports:
        - "444:444"
      environment:
      - CHOKIDAR_USEPOLLING=true
      volumes:
        - ./etsin_finder/:/etsin_finder/
      depends_on:
        - frontend
        - backend
        - elasticsearch

configs:
  etsin-qvain-app-config:
    external: True
  etsin-qvain-nginx-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True
  etsin-qvain-nginx-dhparam:
    external: True
