version: '3'
services:
    frontend:
      container_name: "webpack"
      image: etsin-qvain-webpack-build
      build:
        context: ./etsin_finder/frontend
        dockerfile: etsin_finder/frontend/webpack.dockerfile
      command: npm run dev-build
      ports:
        - "8080:8080"
      volumes:
          - templates:/build
      environment:
        - base_url=0.0.0.0:8080
      depends_on: 
        - backend
    backend:
      container_name: "flask"
      image: etsin-qvain-flask
      command: gunicorn --bind '0.0.0.0:5000' etsin_finder.finder:app --preload
      build:
        context: ./
        dockerfile: flask.dockerfile
      ports:
        - "5000:5000"
      expose:
        - "5000"
      volumes:
          - templates:/build
      environment:
        - base_url=0.0.0.0:5000
        - FLASK_ENV=development
        - PYTHONPATH=/
        - FLASK_DEBUG=1
volumes:
     templates: 