version: '3'
services:
    frontend:
      container_name: "webpack"
      image: etsin-qvain-webpack
      build:
        context: ./etsin_finder/frontend
        dockerfile: etsin_finder/frontend/webpack.dockerfile
      command: npm start
      ports:
        - "8080:8080"
      environment:
        - base_url=0.0.0.0:8080
      depends_on: 
        - backend
    backend:
      container_name: "flask"
      image: etsin-qvain-flask
      command: python etsin_finder/finder.py
      build:
        context: ./
        dockerfile: flask.dockerfile
      ports:
        - "5000:5000"
      expose:
        - "5000"
      environment:
        - base_url=0.0.0.0:5000
        - FLASK_ENV=development
      external_links:
        - webpack:localhost
