version: '3.3'
services:
    frontend:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-qvain-webpack
      command: npm start
      ports:
        - "8080:8080"
      volumes:
        - type: bind
          source: ./etsin_finder/frontend/
          target: /etsin_finder/frontend/
        - type: volume
          source: static_folder
          target: /etsin_finder/frontend/static/
      depends_on:
        - backend
      environment:
        - CHOKIDAR_USEPOLLING=true
        - base_url=0.0.0.0:8080
      networks:
        - elastic-network
    backend:
      image: fairdata-docker.artifactory.ci.csc.fi/fairdata-etsin-qvain-flask
      configs:
        - source: etsin-qvain-app-config
          target: /home/etsin-user/app_config
      ports:
        - "5000:5000"
      volumes:
        - type: bind
          source: ./etsin_finder/frontend/build/
          target: /etsin_finder/frontend/build/
        - type: volume
          source: static_folder
          target: /etsin_finder/frontend/static/
      environment:
        - base_url=0.0.0.0:5000
        - FLASK_ENV=development
        - PYTHONPATH=/
        - FLASK_DEBUG=1
      networks:
        - elastic-network
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - base_url=0.0.0.0:9200
        - http.host=0.0.0.0
        - transport.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
      volumes:
        - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      networks:
        - elastic-network
    nginx:
      image: nginx
      configs:
        - source: etsin-qvain-nginx-config
          target: /etc/nginx/nginx.conf
        - source: fairdata-ssl-certificate
          target: /etc/nginx/ssl_certs/ssl.crt.pem
        - source: fairdata-ssl-certificate-key
          target: /etc/nginx/ssl_certs/ssl.key.pem
        - source: etsin-qvain-nginx-dhparam
          target: /etc/nginx/ssl_certs/dhparam.pem
      ports:
        - "80:80"
        - "443:443"
      environment:
      - CHOKIDAR_USEPOLLING=true
      volumes:
        - type: bind
          source: ./etsin_finder/frontend/build/
          target: /etsin_finder/frontend/build/
        - type: volume
          source: static_folder
          target: /etsin_finder/frontend/static/
      depends_on:
        - frontend
        - backend
        - elasticsearch
      networks:
        - elastic-network
volumes:
    static_folder:
      driver: local
networks:
  elastic-network:
    driver: overlay
    attachable: true
    external: true
configs:
  etsin-qvain-app-config:
    external: True
  etsin-qvain-nginx-config:
    external: True
  fairdata-ssl-certificate:
    external: True
  fairdata-ssl-certificate-key:
    external: True
  etsin-qvain-nginx-dhparam:
    external: True
