version: '3'
services:
    webpack:
      image: etsin-qvain-webpack
      build:
        context: ./
        dockerfile: etsin_finder/frontend/webpack.dockerfile
      command: npm start
      volumes:
        - ./client:/app
      ports:
        - "8080:8080"
    flask:
      image: etsin-qvain-flask
      command: python finder.py
      build:
        context: ./
        dockerfile: flask.dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ./:/app
  