version: '3'
services:
    backend:
      container_name: "flask"
      image: etsin-qvain-flask
      build:
        context: ./
        dockerfile: flask.dockerfile
      ports:
        - "5000:5000"
      expose:
        - "5000"
      volumes:
        - type: bind
          source: ./etsin_finder/frontend/build/
          target: /etsin_finder/frontend/build/
        - type: volume
          source: static_folder
          target: /etsin_finder/frontend/static/
        - type: volume
          source: certificates_folder
          target: /etc/nginx/ssl_certs/
      environment:
        - base_url=0.0.0.0:5000
        - FLASK_ENV=development
        - PYTHONPATH=/
        - FLASK_DEBUG=1
    nginx:
      container_name: "nginx"
      image: etsin-qvain-nginx
      build:
        context: ./nginx/
        dockerfile: nginx/nginx.dockerfile
      ports:
        - "80:80"
        - "443:443"
      expose:
        - "80"
        - "443"
      volumes:
        - type: bind
          source: ./etsin_finder/frontend/build/
          target: /etsin_finder/frontend/build/
        - type: volume
          source: static_folder
          target: /etsin_finder/frontend/static/
        - type: volume
          source: certificates_folder
          target: /etc/nginx/ssl_certs/
      environment:
      - CHOKIDAR_USEPOLLING=true
      depends_on:
      - backend
volumes:
    static_folder:
      driver: local
    certificates_folder:
      driver: local