version: '3'
services:
    webpack:
      container_name: "webpack"
      image: etsin-qvain-webpack
      build:
        context: ./etsin_finder/frontend
        dockerfile: etsin_finder/frontend/webpack.dockerfile
      command: npm start
      volumes:
        - ./client:/app
      ports:
        - "8080:8080"
      environment:
        - base_url=localhost:8080
    flask:
      container_name: "flask"
      image: etsin-qvain-flask
      command: python finder.py
      build:
        context: ./
        dockerfile: flask.dockerfile
      ports:
        - "5000:5000"
      environment:
        - base_url=localhost:5000
      external_links:
        - webpack:localhost
      volumes:
        - ./:/app
